//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.
// Re-generate with: make generate

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VaultEtcdSync) DeepCopyInto(out *VaultEtcdSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of VaultEtcdSync.
func (in *VaultEtcdSync) DeepCopy() *VaultEtcdSync {
	if in == nil {
		return nil
	}
	out := new(VaultEtcdSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VaultEtcdSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of VaultEtcdSyncList into another object.
func (in *VaultEtcdSyncList) DeepCopyInto(out *VaultEtcdSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultEtcdSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of VaultEtcdSyncList.
func (in *VaultEtcdSyncList) DeepCopy() *VaultEtcdSyncList {
	if in == nil {
		return nil
	}
	out := new(VaultEtcdSyncList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VaultEtcdSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of VaultEtcdSyncSpec into another object.
func (in *VaultEtcdSyncSpec) DeepCopyInto(out *VaultEtcdSyncSpec) {
	*out = *in
	if in.VaultPaths != nil {
		in, out := &in.VaultPaths, &out.VaultPaths
		*out = make([]VaultPath, len(*in))
		copy(*out, *in)
	}
	out.VaultRef = in.VaultRef
	in.EtcdRef.DeepCopyInto(&out.EtcdRef)
}

// DeepCopy creates a deep copy of VaultEtcdSyncSpec.
func (in *VaultEtcdSyncSpec) DeepCopy() *VaultEtcdSyncSpec {
	if in == nil {
		return nil
	}
	out := new(VaultEtcdSyncSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of VaultEtcdSyncStatus into another object.
func (in *VaultEtcdSyncStatus) DeepCopyInto(out *VaultEtcdSyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of VaultEtcdSyncStatus.
func (in *VaultEtcdSyncStatus) DeepCopy() *VaultEtcdSyncStatus {
	if in == nil {
		return nil
	}
	out := new(VaultEtcdSyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of VaultPath.
func (in *VaultPath) DeepCopyInto(out *VaultPath) {
	*out = *in
}

// DeepCopy creates a deep copy of VaultPath.
func (in *VaultPath) DeepCopy() *VaultPath {
	if in == nil {
		return nil
	}
	out := new(VaultPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of VaultRef.
func (in *VaultRef) DeepCopyInto(out *VaultRef) {
	*out = *in
}

// DeepCopy creates a deep copy of VaultRef.
func (in *VaultRef) DeepCopy() *VaultRef {
	if in == nil {
		return nil
	}
	out := new(VaultRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of EtcdRef.
func (in *EtcdRef) DeepCopyInto(out *EtcdRef) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of EtcdRef.
func (in *EtcdRef) DeepCopy() *EtcdRef {
	if in == nil {
		return nil
	}
	out := new(EtcdRef)
	in.DeepCopyInto(out)
	return out
}
